COLUMN_NAMES_CONST = {'coa_creation_date':'Fecha de edición',
                      'product_name'     :'ReferenciaQ',
                      'client_code'      :'CódigoQ',
                      'batch_number'     :'LoteQV',
                      'created_date'     :'FEQ',
                      'expired_date'     :'FVQ',
                      'qty_in_boxes'     :'CajasQV',
                      'units_per_box'    :'u_cajaQ',
                      'total_qty'        :'Totalu_Q',
                      'appearance'       :'AspectoQ',
                      'colour'           :'ColorQ',
                      'odor'             :'OlorQ',
                      'density'          :'DensidadQ',
                      'pH_spec'          :'Rango pHQ',
                      'pH'               :'Resultado pHQV',
                      'viscosity_spec'   :'Rango viscosidadQ',
                      'viscosity'        :'Resultado viscosidadQV',
                      'net_weight_spec'  :'Rango peso netoQ',
                      'net_weight'       :'Resultado peso netoQ',
                      'sequential'       :'Consecutivo',
                      'status'           :'Status'}

column_names_var =  { 'coa_creation_date':'Fecha de edición',
                      'product_name'     :'ReferenciaQ',
                      'client_code'      :'CódigoQ',
                      'batch_number'     :'LoteQV',
                      'created_date'     :'FEQ',
                      'expired_date'     :'FVQ',
                      'qty_in_boxes'     :'CajasQV',
                      'units_per_box'    :'u_cajaQ',
                      'total_qty'        :'Totalu_Q',
                      'appearance'       :'AspectoQ',
                      'colour'           :'ColorQ',
                      'odor'             :'OlorQ',
                      'density'          :'DensidadQ',
                      'pH_spec'          :'Rango pHQ',
                      'pH'               :'Resultado pHQV',
                      'viscosity_spec'   :'Rango viscosidadQ',
                      'viscosity'        :'Resultado viscosidadQV',
                      'net_weight_spec'  :'Rango peso netoQ',
                      'net_weight'       :'Resultado peso netoQ',
                      'sequential'       :'Consecutivo',
                      'status'           :'Status'}


# COLUMN_NAMES = {'Fecha de edición'      :'coa_creation_date',
#                 'ReferenciaQ'           :'product_name',
#                 'CódigoQ'               :'client_code',      
#                 'LoteQV'                :'batch_number',
#                 'FEQ'                   :'created_date',
#                 'FVQ'                   :'expired_date',
#                 'CajasQV'               :'qty_in_boxes',
#                 'u_cajaQ'               :'units_per_box',
#                 'Totalu_Q'              :'total_qty',
#                 'AspectoQ'              :'appearance',
#                 'Rango pHQ'             :'pH_spec',
#                 'Resultado pHQV'        :'pH',
#                 'Rango viscosidadQ'     :'viscosity_spec',
#                 'Resultado viscosidadQV':'viscosity',
#                 'Rango peso netoQ'      :'net_weight_spec',
#                 'Resultado peso netoQ'  :'net_weight',
#                 'Consecutivo'           :'sequential',
#                 'Status'                :'status'}