COLUMN_NAMES = {'coa_creation_date':'Fecha de edición',
                'product_name'     :'ReferenciaQ',
                'client_code'      :'CódigoQ',
                'batch_number'     :'LoteQV',
                'created_date'      :'FEQ',
                'expired_date'     :'FVQ',
                'qty_in_boxes'     :'CajasQV',
                'units_per_box'    :'u_cajaQ',
                'total_qty'        :'Totalu_Q',
                'appearance'       :'AspectoQ',
                'pH_spec'          :'Rango pHQ',
                'pH'               :'Resultado pHQV',
                'viscosity_spec'   :'Rango viscosidadQ',
                'viscosity'        :'Resultado viscosidadQV',
                'net_weight_spec'  :'Rango peso netoQ',
                'net_weight'       :'Resultado peso netoQ',
                'sequential'       :'Consecutivo',
                'status'           :'Status'}
